name: Build CI Image

on:
  push:
    branches: [ main, master ]
    paths:
      - 'docker/ci/**'
      - '.github/workflows/ci-image.yml'
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1' # weekly refresh

permissions:
  contents: read
  packages: write

jobs:
  build-push:
    runs-on: [self-hosted, linux, x64, modnet-runner]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./docker/ci
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository_owner }}/modsdk-ci:latest
            ghcr.io/${{ github.repository_owner }}/modsdk-ci:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
